name: 'build'
on: [push]
jobs:
  build-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Testing with CFN Lint Command
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t ./cloudformation/ec2-bastion.yml --region us-east-1 --ignore-checks W